-- Drop the enum type if it already exists
DROP TYPE IF EXISTS public.account_type;

-- Create the account_type enum
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Classification table
CREATE TABLE public.classification(
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric (9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create the relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

-- Create the 'account' table
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Insert data into 'classification' table
INSERT INTO public.classification(classification_name)
VALUES ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- Insert data into 'inventory' table
INSERT INTO public.inventory (
        inv_make,
        inv_model,
        inv_year,
        inv_description,
        inv_image,
        inv_thumbnail,
        inv_price,
        inv_miles,
        inv_color,
        classification_id
    )
VALUES (
        'Chevy',
        'Camaro',
        '2018',
        'If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!',
        '/images/camaro.jpg',
        '/images/camaro-tn.jpg',
        25000,
        101222,
        'Silver',
        2
    ),
    (
        'Batmobile',
        'Custom',
        '2007',
        'Ever wanted to be a super hero? Now you can with the Batmobile. This car allows you to switch to bike mode to easily maneuver through traffic during rush hour.',
        '/images/batmobile.jpg',
        '/images/batmobile-tn.jpg',
        65000,
        29887,
        'Black',
        1
    ),
    (
        'FBI',
        'Surveillance Van',
        '2016',
        'Do you like police shows? You will feel right at home driving this van, complete with surveillance equipment for an extra fee of $2,000 a month.',
        '/images/survan.jpg',
        '/images/survan-tn.jpg',
        20000,
        19851,
        'Brown',
        1
    ),
    (
        'Dog',
        'Car',
        '1997',
        'Do you like dogs? This car is for you. Straight from Aspen, Colorado, we have the original Dog Car, complete with fluffy ears.',
        '/images/dog-car.jpg',
        '/images/dog-car-tn.jpg',
        35000,
        71632,
        'White',
        1
    ),
    (
        'Jeep',
        'Wrangler',
        '2019',
        'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Great for everyday driving as well as off-roading, whether on the rocks or in the mud!',
        '/images/wrangler.jpg',
        '/images/wrangler-tn.jpg',
        28045,
        41205,
        'Yellow',
        3
    ),
    (
        'Lamborghini',
        'Adventador',
        '2016',
        'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws.',
        '/images/adventador.jpg',
        '/images/adventador-tn.jpg',
        417650,
        71003,
        'Blue',
        2
    ),
    (
        'Aerocar International',
        'Aerocar',
        '1963',
        'Are you tired of rush-hour traffic? This car converts into an airplane to get you where you’re going quickly. Only 6 of these were made, get them while they last!',
        '/images/aerocar.jpg',
        '/images/aerocar-tn.jpg',
        700000,
        18956,
        'Red',
        1
    ),
    (
        'Monster',
        'Truck',
        '1995',
        'Most trucks are for work, but this one is for fun. This beast comes with 60-inch tires for traction needed to jump and roll in the mud.',
        '/images/monster-truck.jpg',
        '/images/monster-truck-tn.jpg',
        150000,
        3998,
        'Purple',
        1
    ),
    (
        'Cadillac',
        'Escalade',
        '2019',
        'This stylish car is great for any occasion, from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
        '/images/escalade.jpg',
        '/images/escalade-tn.jpg',
        75195,
        41958,
        'Black',
        4
    ),
    (
        'GM',
        'Hummer',
        '2016',
        'Do you have 6 kids and like to go off-roading? The Hummer gives you small interiors with an engine to get you out of any muddy or rocky situation.',
        '/images/hummer.jpg',
        '/images/hummer-tn.jpg',
        58800,
        56564,
        'Yellow',
        4
    ),
    (
        'Mechanic',
        'Special',
        '1964',
        'Not sure where this car came from. However, with a little TLC, it will run as good as new.',
        '/images/mechanic.jpg',
        '/images/mechanic-tn.jpg',
        100,
        200125,
        'Rust',
        5
    ),
    (
        'Ford',
        'Model T',
        '1921',
        'The Ford Model T can be tricky to drive. It was the first car to be mass-produced. You can get it in any color as long as it’s black.',
        '/images/model-t.jpg',
        '/images/model-t-tn.jpg',
        30000,
        26357,
        'Black',
        5
    );

-- INNER JOIN query to retrieve sports cars
SELECT inv_make, inv_model, classification.classification_name
FROM inventory
INNER JOIN classification
    ON inventory.classification_id = classification.classification_id
WHERE classification.classification_name = 'Sport';

-- UPDATE QUERY to modify image paths

UPDATE inventory
SET 
    inv_image = CONCAT(
        SUBSTRING(inv_image FROM 1 FOR POSITION('images' IN inv_image) + 5), 
        '/vehicles', 
        SUBSTRING(inv_image FROM POSITION('images' IN inv_image) + 6 FOR LENGTH(inv_image))
    ),
    inv_thumbnail = CONCAT(
        SUBSTRING(inv_thumbnail FROM 1 FOR POSITION('images' IN inv_thumbnail) + 5), 
        '/vehicles', 
        SUBSTRING(inv_thumbnail FROM POSITION('images' IN inv_thumbnail) + 6 FOR LENGTH(inv_thumbnail))
    );